import { useEffect, useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import {
  auth,
  onAuthStateChanged,
  signOut,
} from "../firebase/index.jsx";
import Layout from "../components/Layout.jsx";

export default function DashboardPage() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null);

  // Chat state
  const [messages, setMessages] = useState([
    {
      id: 1,
      role: "assistant",
      content:
        "Hi, I’m your MedAssist assistant. Share the medications you’re taking or the instructions your doctor gave you, and I’ll help break everything down in simple, easy-to-follow terms.\n\nI can explain what each medicine is for, suggest a clear example schedule, highlight common side effects, point out general interaction concerns, and offer basic tips for managing mild symptoms.\n\nJust type something like: \"Ibuprofen 400mg as needed, Lisinopril 10mg daily, Claritin 10mg daily, can these mix and when should I take them?\"",
      createdAt: new Date().toLocaleString(),
    },
  ]);
  const [input, setInput] = useState("");
  const [isSending, setIsSending] = useState(false);
  const chatEndRef = useRef(null);

  // ---------------------------------------------------
  // AUTH GUARD GENERATED BY GITHUB COPILOT
  // ---------------------------------------------------
  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (u) => {
      if (!u) navigate("/login");
      else setUser(u);
    });
    return () => unsub();
  }, [navigate]);

  // Scroll to bottom on new messages
  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages]);

  // GitHub Copilot wrote this: async handler to simulate assistant response and reset sending state
  async function handleSend(e) {
    e.preventDefault();
    const text = input.trim();
    if (!text || isSending) return;

    setIsSending(true);

    const userMsg = {
      id: Date.now(),
      role: "user",
      content: text,
      createdAt: new Date().toLocaleString(),
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput("");

    try {
      const token = await auth.currentUser.getIdToken();

      const res = await fetch("http://localhost:4000/api/summarize", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ instructions: text }),
      });

      const data = await res.json();

      if (!res.ok) throw new Error(data.error || "Failed to summarize");

      const assistantMsg = {
        id: Date.now() + 1,
        role: "assistant",
        content: data.summary,
        createdAt: new Date().toLocaleString(),
      };

      setMessages((prev) => [...prev, assistantMsg]);
    } catch (err) {
      console.error(err);
      const errorMsg = {
        id: Date.now() + 2,
        role: "assistant",
        content:
          "Sorry, I couldn’t summarize those instructions right now. Please try again shortly.",
        createdAt: new Date().toLocaleString(),
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsSending(false);
    }
  }

  if (!user) {
    return (
      <Layout>
        <div className="text-gray-600">Loading...</div>
      </Layout>
    );
  }

  return (
    <Layout userName={user.displayName || user.email}>
      <div className="flex flex-col h-[calc(100vh-5rem)]">

        {/* Page header */}
        <div className="mb-3">
          <h2 className="text-2xl font-semibold">Medical Assistance</h2>
          <p className="text-sm text-gray-600">
            Ask questions about your medical instructions or paste what your
            doctor provided. I’ll help explain it in clearer, friendlier terms.
          </p>
        </div>

        {/* Chat container */}
        <div className="flex-1 min-h-0 bg-white border rounded-lg shadow-sm flex flex-col">
          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-3">
            {messages.map((msg) => (
              <ChatMessage key={msg.id} message={msg} />
            ))}
            <div ref={chatEndRef} />
          </div>

          {/* Input area */}
          <form onSubmit={handleSend} className="border-t p-3">
            <div className="flex gap-2 items-end">
              <textarea
                className="flex-1 border rounded-md p-2 text-sm resize-none max-h-32 focus:outline-none focus:ring-2 focus:ring-blue-500"
                rows={2}
                placeholder='Example: "Take 1 tablet of Lisinopril 10mg by mouth once daily in the morning. Stop if you notice severe dizziness."'
                value={input}
                onChange={(e) => setInput(e.target.value)}
              />
              <button
                type="submit"
                disabled={isSending || input.trim().length === 0}
                className="bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-700 transition disabled:opacity-60"
              >
                {isSending ? "Thinking..." : "Send"}
              </button>
            </div>
            <div className="text-xs text-gray-500 mt-1">
              Do not use this prototype for real medical decisions.
            </div>
          </form>
        </div>
      </div>
    </Layout>
  );
}

// ---------------------------------------------------
// CHAT BUBBLE COMPONENT GENERATED BY GITHUB COPILOT
// ---------------------------------------------------
function ChatMessage({ message }) {
  const isUser = message.role === "user";

  return (
    <div className={"flex " + (isUser ? "justify-end" : "justify-start")}>
      <div
        className={
          "max-w-xl rounded-lg px-3 py-2 text-sm whitespace-pre-wrap " +
          (isUser
            ? "bg-blue-600 text-white rounded-br-none"
            : "bg-gray-100 text-gray-900 rounded-bl-none")
        }
      >
        {message.content}
        <div className="mt-1 text-[10px] opacity-70 text-right">
          {message.createdAt}
        </div>
      </div>
    </div>
  );
}
